version: "3"

services:
  www:
    build:
      context: .docker/www
      dockerfile: Dockerfile
    container_name: www
    volumes:
      - .:/var/www/html/
    ports:
      - "80:80"
      - "443:443"
    tty: true
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root